apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: layer7
resources:
  - ./namespace.yaml
generatorOptions:
 disableNameSuffixHash: true
configMapGenerator:
  - name: healthcheck-scripts-configmap
    files:
      - "./scripts/healthcheck/001_healthcheck.sh"
      - "./scripts/healthcheck/002_healthcheck.sh"
    # - "./scripts/healthcheck/base.sh"
  - name: config-override-configmap
    files:
      - "./properties/sampletrafficloggerca.properties"
      - "./properties/ssg.security"
secretGenerator:
  - name: ssg-secret
    env: gateway.env
  - name: init-secret
    env: init.env
  - name: ssg-license
    files:
      - "license"
  - name: healthcheck-scripts-secret
    files:
      - "./scripts/healthcheck/001_healthcheck.sh"
      - "./scripts/healthcheck/002_healthcheck.sh"
    # - "./scripts/healthcheck/base.sh"
  - name: config-override-secret
    files:
      - "./properties/sampletrafficloggerca.properties"
      - "./properties/ssg.security"