license:
  accept: true

image:
  registry: docker.io
  repository: caapim/gateway
  tag: 11.1.2
  pullPolicy: IfNotPresent

pmtagger:
  enabled: true

# Diskless Configuration modes for the Gateway
disklessConfig:
  # true - environment variables are used for gateway configuration
  # false - node.properties is used for gateway configuration
  enabled: false
  # true - node.properties is set by initContainer and bootstrap script
  # false - node.properties is set by existingSecret
  setSecretByInitContainer: true
  existingSecret: {}

management:
  service:
    enabled: true

# use the service Account name created in AWS
serviceAccount:
  name: gw-sa
  create: false
# If pmtagger is enabled the Gateway Service Account will need to have
# list/patch permissions for Pods.
rbac:
  create: false

database:
  enabled: false
  create: false
  liquibaseLogLevel: "warning"

# Add initContainers to the Gateway
initContainers:
  - name: aws-init
    image: amazon/aws-cli:latest # or your selected version
    env:
      - name: AWS_REGION
        value: us-west-2 # or your-aws-region
    volumeMounts:
      - name: shared-secret
        mountPath: /opt/docker/config
    command: ["sh", "-c"]
    args:
      - |
        set -e
        # Fetch secret from AWS, replace secret-id with your node.properties secret name
        aws secretsmanager get-secret-value --secret-id gateway.node.properties --query SecretString \
          --output text > /opt/docker/config/node.json

        # Parse JSON into .properties format
        yum install -y jq
        jq -r 'to_entries | map("\(.key)=\(.value)") |.[]' /opt/docker/config/node.json > /opt/docker/config/node.properties

ingress:
  # Set to true to create ingress object
  enabled: true
  # Ingress Class Name
  ingressClassName: apim-nginx
  # Ingress annotations
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
  rules:
    - host: gateway1.aws.apimdev.org
      path: "/"
      service:
        port:
          name: https
