license:
  accept: true

image:
  registry: docker.io
  repository: caapim/gateway
  tag: 11.1.2
  pullPolicy: IfNotPresent

imagePullSecret:
  enabled: true
  existingSecretName: devlocalproxy

pmtagger:
  enabled: true

# Diskless Configuration modes for the Gateway
disklessConfig:
  # true - environment variables are used for gateway configuration
  # false - node.properties is used for gateway configuration
  enabled: false
  # true - node.properties is set by initContainer and bootstrap script
  # false - node.properties is set by existingSecret
  setSecretByInitContainer: true
  existingSecret: {}
    #     name: gateway-secret
    # true - secret store as property format (multi-line)
  # false - secret store as non-property format (single-line)
#     csi:
#        driver: secrets-store.csi.k8s.io
#        readOnly: true
#        volumeAttributes:
#          secretProviderClass: db-aws-secrets
#     setByInitContainer: ture

management:
  service:
    enabled: false

# use the service Account name created in AWS
serviceAccount:
  name: gw-sa
  create: false
# If pmtagger is enabled the Gateway Service Account will need to have
# list/patch permissions for Pods.
rbac:
  create: false

database:
  enabled: false
  create: false
  liquibaseLogLevel: "warning"

# Add initContainers to the Gateway
initContainers:
  - name: aws-init
    image: amazon/aws-cli:2.15.0
    command:
      - sh
      - -c
      - |
        set -e
        # Fetch secret JSON from AWS
        aws secretsmanager get-secret-value \
          --region us-west-2 \
          --secret-id gateway.node.properties \
          --query SecretString \
          --output text > /opt/docker/conf/node.json

        # Parse JSON into .properties format
        apk add --no-cache jq > /dev/null 2>&1 || yum install -y jq || true
        jq -r '
          to_entries |
          map("\(.key)=\(.value)") |
          .[]' /opt/docker/conf/node.json > /opt/docker/conf/node.properties
    # volumeMount name shared-secret is required for successful mounting to final location by Gateway container
    volumeMounts:
      - name: shared-secret
        mountPath:  /opt/docker/conf

ingress:
  # Set to true to create ingress object
  enabled: true
  # Ingress Class Name
  ingressClassName: apim-nginx
  # Ingress annotations
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
  rules:
    - host: tz670296-gateway1.aws.apimdev.org
      path: "/"
      service:
        port:
          name: https
